# Generated by Django 3.0.9 on 2020-08-13 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('h1', models.CharField(blank=True, default='', max_length=250, verbose_name='H1')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Заголовок')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='Keywords')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='Полный URL')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='')),
                ('icon', models.ImageField(blank=True, default='', null=True, upload_to='category_images')),
                ('product_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Колличество товаров в категории')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category', verbose_name='Категория родителя')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImportedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('sync_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='ID синхронизации')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('equivalent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_categories', to='catalog.Category', verbose_name='Эквивалентная категория')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.ImportedCategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Импортированная категория',
                'verbose_name_plural': 'Импортированные категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='category_banners', verbose_name='Изображение')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='')),
            ],
            options={
                'verbose_name': 'Баннер категорий',
                'verbose_name_plural': 'Баннеры категорий',
                'ordering': ['order'],
            },
        ),
    ]
