# Generated by Django 3.0.9 on 2020-08-13 06:09

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='advantages', verbose_name='Иконка')),
                ('first_title', models.CharField(max_length=255, verbose_name='Первый заголовок')),
                ('second_title', models.CharField(max_length=50, verbose_name='Второй заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BannersMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название баннера')),
                ('image_desktop', models.ImageField(blank=True, upload_to='main_banner', verbose_name='Баннер десктопа')),
                ('image_mobile', models.ImageField(blank=True, upload_to='main_banner_mobile', verbose_name='Баннер мобильный')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок баннера')),
                ('text', models.CharField(blank=True, default='', max_length=255, verbose_name='Текс баннера')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка с баннера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Баннер на главной странице',
                'verbose_name_plural': 'Баннеры на главной странице',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CallBackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('1', 'Форма обратной связи'), ('2', 'Связаться с нами'), ('3', 'Хотите сотрудничать')], default='1', max_length=1, verbose_name='Тип формы')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'ФОС Заказать звонок',
                'verbose_name_plural': 'ФОС Заказать звонок',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование сертификата')),
                ('image', models.ImageField(upload_to='certificates', verbose_name='Фото сертификата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FinishedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='finished_works', verbose_name='Фото работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Готовая работа',
                'verbose_name_plural': 'Готовые работы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainNavItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('image', models.FileField(default='', upload_to='main_nav', verbose_name='Картинка')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Раздел основной навигации',
                'verbose_name_plural': 'Разделы основной навигации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='managers_images', verbose_name='Фото')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('family_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('additional_number', models.CharField(blank=True, max_length=255, verbose_name='Добавочный номер')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('messenger', models.CharField(blank=True, max_length=60, verbose_name='Мессенджер')),
                ('social_network', models.CharField(blank=True, max_length=255, verbose_name='Социальная сеть')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SearchPlaceholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=250, unique=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Текст для строки поиска',
                'verbose_name_plural': 'Тексты для строки поиска',
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255, verbose_name='Содержимое тега Title')),
                ('page_decription', models.CharField(max_length=255, verbose_name='Содержимое тега Description')),
                ('seo_text_1', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='SEO текст 1')),
                ('seo_text_2', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='SEO текст 2')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email подписчика')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=' Имя Фамилия сотрудника')),
                ('position', models.CharField(max_length=255, verbose_name='Должность сотрудника')),
                ('image', models.ImageField(upload_to='team_members', verbose_name='Фото сотрудника')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел верхнего меню',
                'verbose_name_plural': 'Разделы верхнего меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='Полный адрес')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Содержимое тега title')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Содержимое тега description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Содержание')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Статическая страница'), (1, 'Страница каталога')], default=0, verbose_name='Тип страницы')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название пользовательского шаблона страницы')),
                ('dop_template', models.CharField(blank=True, default='', max_length=150, verbose_name='Допoлнительный HTML контент')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Pages.Page', verbose_name='Страница родителя')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'get_latest_by': 'created_at',
                'abstract': False,
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
