# Generated by Django 3.0.9 on 2020-08-13 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('completed', models.BooleanField(default=False, verbose_name='Оформленный заказ')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', max_length=30, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('layout', models.FileField(blank=True, default='', upload_to='layout', verbose_name='Макет')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
    ]
