# Generated by Django 3.0.9 on 2020-08-13 06:09

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Наименование')),
                ('intro_text', models.TextField(blank=True, default='', verbose_name='Короткий текст')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Контент')),
                ('image', models.ImageField(blank=True, default='', upload_to='article_image', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать')),
                ('seo_title', models.CharField(max_length=255, verbose_name='Title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('has_button', models.BooleanField(verbose_name='Кнопка оформления заявки')),
                ('is_video_review', models.BooleanField(default=False, verbose_name='Видеообзор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
